---
development:
  cloud_name: dr9nwzu4f
  api_key: <%= Rails.application.credentials[:development][:cloudinary][:api_key] %>
  api_secret: <%= Rails.application.credentials[:development][:cloudinary][:api_secret] %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dr9nwzu4f
  api_key: <%= Rails.application.credentials[:production][:cloudinary][:api_key] %>
  api_secret: <%= Rails.application.credentials[:production][:cloudinary][:api_secret] %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dr9nwzu4f
  api_key: <%= Rails.application.credentials[:test][:cloudinary][:api_key] %>
  api_secret: <%= Rails.application.credentials[:test][:cloudinary][:api_secret] %>
  enhance_image_tag: true
  static_file_support: false
